default_roles:
  - system
  # - bash
  - docker
  - git
  - go
  - helm
  - k8s
  - neofetch
  - neovim
  - python
  - rust
  - ssh
  - sshfs
  - terraform
  - tmux
  - zsh

git_user_name: "Eusebio Resende"

git_user_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33366136653530316637663461653261373035343364623737393262333337373561623633373966
  3131333134316331333262613266356265353731656432330a636561633033376266333630656662
  36393561663836373036396461623061353462333562373833376434356262306330643536336631
  3365353763383563620a386265643236613435633563616164306632633261306635373437373939
  62656637313433663030356638656564383837623430653265613435303066313039
work_computer: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62653730363934393937656462303462353665633666393434636664393334663135393266363162
  3631343063383362313436346530356539303234356335330a313439346539343864616433666632
  66333532653732663130333930656130623739643563313266343162616261336436386463646436
  3766346435323138300a653461633966383762666161633636396130373534316635646364313939
  3635
ssh_key:
  id_rsa: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    66353861343166323035383939366431616566613034663134373931663165626237363263623031
    6239303039306337323237386531623262376137353034650a623562353730653831366266346565
    66303235383636313461663461306261313766663133376531336236633865316532653765353230
    3861343461353066330a663731636234396661393836303130663036343066656165666639346335
    38373437353732663561323166623135353535323530663439633832366466323039663665386663
    37613231353333656161656261376462303539336663316531666135646239653431643236323464
    66383163373763333635613834613633646364313835613336363863306131636439336230343732
    36323761643761633465363839646561326365303932663764346466636439323366383965323938
    32633537306663616634323161353535626131373737373337646465306362383631326434626531
    34376234343066656239623761346163383633343134313164663964313138346466386134303239
    61623937393361663232396264306665383162633636333839333835396261666233356661623831
    38636434376630303762333863366234303033356533663464386631383034373632613063373461
    62353435653833656632623932393835303532353735393764363235626531356635363837356132
    30613230346461373161393739336464656662393665646635316334303439663835303939663735
    39626131303133616231336265663435323634623432626330643635393033383635343630356534
    33333230343532663134333233323634373637326436336234383738653562376432663837323661
    30373339653164663862653664373964326264656338636165373439313131646234356231383761
    36333765626437303339346230316434646536646163636461633334666163326361643864383636
    36346131633236623030326532616238623262623934616461613961373636623265623264393463
    34303334373763343264323730633436303638633230636237646538303936333137613439366235
    30326130303264663034663962323563613537366530613430636665396465316532346234656439
    35396432393963616562316365653165316566303036333132623637393035646363316636323930
    35373531383434663565626438646364613035356362396665643066393263626365386635356462
    33373361386663626464636562626635373331653939646665626234303563366236356637393836
    33323066373334313134653334396166306536613965356438353133396562306166636435386565
    33333761386430663935646631396437633866343738356533303364326633663031653037383839
    38333433636365663861343237353362303565663861356364623131613864643635623235643137
    64633631623361373035373266363733303039646161643336383634643562613563386263666261
    64363339373932333662346666346166386433636564343664353464346165653132663831346435
    33626230323561366332636261623837373132633736313463323264666361393932653365623065
    36663034376264363333653162666134383132343262303739306239346338363139616134666435
    63356266343732666130613431373363396437336363333463373535383063656233393266326637
    36393166643262303530393230303766396233633434666566343865633461376262363462633063
    37376234643338616434363363303763356435623337386563643865623062303139353163383965
    34303932633666633236343731613937623361626164343833366131393830643136333539613731
    31393162383361323332636539376262626636383635626165653338343738356133306162623463
    31633139376638353337316334326666346264663834393363383562663236313061346432646566
    32393062616238343864353733386164356266653933363761316339383762343466343661656636
    34333665613034303334363165613535336137363166376464343230653136653063386365633534
    33613136626161613366383839343932363635306564613462656265643038376535323536656531
    39643961393636613862336234633864653763653739313836666562366662303638663564653230
    32393635313165313566323735326461623635666337656534303132616135663936633934333338
    64383431336130343765366161616337643162316438643864366333353161393733343565323266
    62393463343839386232663432626138326138356239623161396431626333646631333863316434
    62663237353962323537313065666263323865306561323561626464306437393565666366663761
    64373231666331323933363139343632626563653139653839633866356437346466353064666533
    30616663383334393139396261393933666164623031626163313531366430656137636537613337
    31383633663331623137306365616239366434623766363762303864393163373163323330336462
    37386130613961326532393435326665396435346234623834656163353636393265366536666335
    66643236663237363764333738396563306535383037396339616236663138323864613933653363
    35393438333464343839343135633733613239643263326661366662383363623537653939643933
    39363732666164313036373464633234303233386333363162656639656433333963613866663638
    34323664373437653539333230633766663839353532363631306364623937656365386565636136
    35666239376237663632333634636539346563376161353961376338613538616163333931396363
    64336134316564396565623334613766616339393166396239306365323738316464316532343235
    39366234316435666163613261316336313365643961353531376430343133636337393166656535
    39643938313436646630656565633334303630666134633534336232323865653430396231353561
    65643866646230313031643633363238336434616538396162323530363930386132663966333233
    33653533653861346163363466393035623531366438393066343761633238613839353539336534
    64333733663264393834646165626234343133656233316131336638643965366364633435356437
    63353037653833326133383637373865376362666265383565653436333838373165343433326631
    33306466356631653562613062316438623033663766366637623737633832326566623030303765
    62613133383039326165393930363933313835613639663332326439333661633661653965613261
    66343037636439323361333263333034633731363834643439623665306537373937646136633962
    36303330313061376661623734343965663735386465393936303761333633363136386439643661
    31363162343833396635616433393533653336393264363961393933633333336132363237383935
    63313739393635346237353366366232386530353134366234306639363335393230646161346435
    63313537643962346461653933326437363037613232326163653064386132623937646632313566
    39633835393962306362356138336233613537306266353866363733346534376230313536633661
    37356530663738313132313563376664663163643964393062306530616234383334323037343537
    63343938353032623432393465343833626462613063396238383362366438656430323531623638
    66623863646636326234363861613831333338363338343639303830313434393964353264666535
    37396461636132386536386561626261326235373832346133646138353139656531396635613335
    39313164393331623063376666633239666336353839613663343431643266343836613534353262
    34343963313562663063313866353861636331306636393236373737383437643766383166646133
    35316566626664393838316162323631373366363933333465326465366563643536323834363634
    39393331303866383936333363643530633062666131343434613333386433323432303264383735
    63623732366266656261633761636133646130316533643434646565393861363937366634633333
    66376562316162326366663665633832396366373365343831663965373930313037353039616131
    65316434636532326236363430373030336139653733353732363066336236656332613339323035
    63343233306331373438626564373035303735363133376463626263346366326465313936613533
    39323536383839336531646437643934353832353561623565346234366261363830333136356434
    63323561613438366331326537366361646365383862373736643135373536393134353230643261
    65353630306631326231613238666432373365353361363861653666616364326161623834626534
    66336236306665626330613631346532306130373766346339386334386664616235346539316261
    39633639613966633165306136623036303238316363353731376538383639666532343239336630
    66636532353561316161616365353439313934323331663232383261353962393265353038323338
    39643065343134653931313434653463356135666334643834613639353861613535643831346438
    61373763383162393265643038303663333639306534313532316333356539386635343730353764
    65663130663465623234623265323333646262653836353032353731663936346261336364663562
    36373834316536646232373434313835353037626663303265313364656533663164653532633539
    66316637326535376337316266383935346462306231353631366263663131656661313230613230
    63326564373739633432313764373033633330363237623735353639623334393964623233363234
    63326638356634303638303834313665343135373336323138633531616463663763326134623766
    31306334663430333962353337633331646361636536336132303263386261653561636563326564
    63626136626461643063323732343261613632653631663335626561323965653361386535376432
    65383635346663626262653639386263336230306436636564643762326335333664626664373239
    66343364333033306634653134646535666132646434376562386336356662353832656566306137
    63323966373066663164363536326664633134396464383232316366663838386632373535316666
    35343963383765306334346435313733376330353035613737356439393033303231626238393032
    38663563663635616131346631363565356164346464343537363564663765303237373739393731
    31336562666661353031646436353866656461313033656233613132333134333364356266623833
    32323066636561363239363239353539656262373266363365376162393566396261656231313239
    32326535353636373531326236643338336135333032366162383362616233383732636235343937
    35616566356665313966336564613162346562366563643035653465646639616132646432323038
    38353234626138303330653434333666306465663336376432373039376665323330333330343364
    36326335636666333665616165666264356631316139653761623061613566376231613638633833
    61623563623866393339393132323665363033343835363739396336616139303632323331373230
    35393161336330336230373835376439656466646331396464326265326433653163333434396435
    31643739306535313466346634623236613336646138343434646366323334643830633135343931
    39663730333530303533643235343237343135363063306638386465646333396333383165346630
    34393235313432313133643737363661376264343362633538623064323765313532616631363665
    38613132333165336264336361333535663736393962346334343235393862303139653065363937
    63643862306635323533616535356362393039343633643764393063643562363563303038623439
    35303261303539376135393235343139363533663066326165353636663961636135303139633863
    36653765623661343232646661633131666364313235306130303234333235303763623466323265
    36363264666437623931613461393466313162356139633532623665316636393034383330356465
    35376463353765363164313733383534643963343537666632303539313466303236323266393162
    61663365353063666166393962393062323331666466343037356333663864303062303765313039
    65656166666134633462653632633731366365386430316533333638363735383937316166336364
    65323866666462396236303130633161623265663635636433373538366166353164363436343461
    35363666343864386230633864383030666665363861306139356630373863326662303033386130
    30306530343566353531633839363566323735393533383864653733626636346334666366333230
    64646662623430663939633461316662356535613035666631373333356665306665366631306361
    64316231646232323663363766393831633532306332303363613339306530333835373866626364
    66363135366137313237396264346334336530323166646139393635316161396464626637623166
    61663531643533323436383533333564323932363762626565383965383464336463666164626365
    38646139333161346535633364303237616136323039353336366161373465376366643431363230
    34623263306130336137326465326164643837656163633437656236626533313562376662333662
    31616463616163653936333666623932646535353961333562383435326331646263663430356232
    33333437613962383030636530373565373161343030353362613062363636336665396532316439
    61373837366538373634326538363339623863653966626332326634633130613033346130656137
    33393932633138616130323334633139306332616130316230653634346666646133663232313662
    39333163643064653433313731653265393735346564646366643831333561633231333736333030
    64323263363435316164646235323064623937653330396532356162376236383036623434353934
    66363835326236363135376531363230663038346333396530643361633931386431636330363461
    62656430336635343833613036326238386137613565663761333461636234613663376165353663
    32666537366632313330366465653266373736333661636334373934346565636432613265383433
    37363062396332373465363137623133643662316461333764643838313435313339656661643064
    37666263663236333834623063393166373735636361623164636664353661306631623636326530
    34326335356339366336306533366337333235363631643235316331353465333366366331643831
    36633533393463353231646139336363373165396564326238663932646239383739343166316634
    65336663343238626638393761663963616139646337623664643534666133306261393636336530
    33393332626165393861396464346634356664623434343738336237376635633862343665393763
    62646131613433646635633135353738646234656463343963636630323634616266653236306263
    66653037326336393066366239303635613537386233343131616435363934613031336535653237
    66323532393537633630653661346432303861303239396638343661626662633832356532613539
    32343862616362643236646165356563316433633333356361626564623732363161333533383134
    34353139613238353635386661303132323562636637336263363063623165393837313239393731
    33663864306462326139666533643234356135656536623139383235656161383661613935343366
    63363539376465643932313639633937336437666634633830663233646465613063383762376232
    30663764356631353138666134393336396261636238393862623665303036343036366436323065
    66383539616166333663336238623330613661666637386461633637326665613936393732613962
    36346166663563383166366438343561643735636230626466393532666337363763336138303363
    65356531343337643066363430323735656437383638636165383461653465376336626437303835
    32623536323634333264323233353462383166323965643662393732393461373438623061346164
    66303565666334336438613866333332343363376530396162363038373136383832313034303166
    30393563623235356537633635323831376363386265393963356263336662616138313561346630
    64363139333263353665366134363132633231333765336231623564626364616331333832323237
    63366636646164353966396632376361376366343766326235643662643735336365323939376665
    38653963353338663433666230323761323530323235313632376138666265613363366332636332
    37366437626239383934326563313637396636633262666462303630383065303364316138306162
    36383033616431663030633533626339356163313963373838313037343265666563323332333138
    62626464303336316634326539306235313134353830346464663235363432376262666632396632
    61396132646532346638326430613631653231336265616139353434303239366534333565343635
    30633261663937333730656637313461313538636637373030366531336462373831646362653131
    61663336616336346565306163646331316363333731386631663864366365333637656261663564
    64306666353737333932303266653031623262343835373163306137306662643831326366313237
    31356561633236613966393339646334386135613933646135336535366431316161346461393230
    63663063333563336236373836363730623664306639353431313730663161306536366632383363
    63333935633033323533646162653436373436666133636361313737653665303038623238626235
    61343136363666633034616237363361623436643564636134316536343530323761316637383730
    35636166326465636236653234613762343336303234393261346364646430306265

  id_rsa.pub: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35306235383964383534366230633662626438393061626261333437616336633466643565613362
    3461323339393630366262383862383766333939663837660a616532333031333461633362383036
    37363165613362383733613937363932383564303265636464636439663334653066646537313061
    6463373662376133360a306563306439666237646662346437636630633038643332336335333635
    63396433346432366463313064313836623038336632623839346638363439633963613438366462
    37326330303965386630323830363132346335313937323036333864313239306262613162656561
    61346539373532383364663838646231303330306335613032386466373938363137666662396439
    37333335643466306235636631653531376539383031633132626432613633346364646331363833
    33653639626364376562346134613339613163343538383463336161346230323064313931353738
    34306563353566663730313331373933363533336633393862316239393662616433643165366262
    38306534656666393537356665376666363332666336636166373930363265363863313438333165
    62313130643365616334363832653161323263643463636462363030663038323939323361623362
    62393732326438333730323563306563356637386563373634383438356130653964623431633138
    64386335303439646633646636656334613135323239363538363262666336616365613033633938
    62353062616665356165323564376631376437343839326266313333333564643032353265646161
    34626466623935316632396133656334666339616166316233303932636265393764633236323534
    34393461613631316263346362373734386333616533316531623738336238366633373931376661
    33393835376437303463663663343962643539613235323636653138376430613938616332396138
    38653838366430663131393535386132323665346137663563343832333132653666316363336132
    61313432653137623862636131613836636265336139323531326237313962323135313031643130
    34626131656538313862343439656534376364306231373766323033363663643535363139626137
    62386162333864323465333338393834323231343835393466353130613963656632373535313030
    62653033366631393065363834633636306430323534626630313865353935333861633130663538
    31646362396562376232396231316235623531363433396234656337333032353436373934663938
    38386638616666663735376133636266326166333963383634373361663736616239653764393738
    63303535303430356364313666326232626232363537623662363031333863363233313431663033
    62383262613962333161633631363330363037383063663536316230663032323932643164366663
    65343137383734613766653938303761633632333932653161613933373632353531613936303766
    32363462643232353165653834343661383631653936613564306466646437643337316161363265
    61646261393739373961306265626661383237653935396237323239633032633831366634613632
    34613666616239393339646230316137316338663639386336383262336465393564303632356439
    63353962313062666637393634663139613733356532323735356633386337666337313362336539
    63616633343434653333346535376362363666653335373030393963333032633763366662326564
    32393633383833356366366562653566333961343265663866613936306362613235653238643661
    64323636633362656661363639393161393864313432396539326630363637313966346566393932
    39326666326633646139633662386335663736636633336232613563636265626338623964613332
    65363739623838636161376131326635303566313430333933306464346465323934353734393239
    36383537613066666134306561373639633463613731663838653961366431396536663163636630
    63623136653237653938333365396436616261626135653234363135613364313763616131383236
    37616132613635323565393130363461383264333831653234666534346139616564306234343936
    32383633336238643462383662303234396134336166393138346265343838353666


k8s:
  repo_version: "v1.28"

